[package]
name = "barretenberg_wrapper"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.2"

[build-dependencies]
bindgen = "0.64.0"
pkg-config = "0.3"
