name: Rust

on: [push, pull_request]

jobs:
  check_n_test:
    name: cargo check & test
    uses: noir-lang/.github/.github/workflows/rust-test.yml@main
    with:
      working-directory: "./barretenberg_wrapper"

  clippy:
    name: cargo clippy
    uses: noir-lang/.github/.github/workflows/rust-clippy.yml@main
    with:
      working-directory: "./barretenberg_wrapper"

  format:
    name: cargo fmt
    uses: noir-lang/.github/.github/workflows/rust-format.yml@main
    with:
      working-directory: "./barretenberg_wrapper"
